import { Inter } from "next/font/google";
import "./globals.css";
import Cabecalho from "@/componentes/cabecalho";
import Rodape from "@/componentes/rodape";


const inter = Inter({ subsets: ["latin"] });



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body suppressHydrationWarning={true}>
      <Cabecalho />
      {children}
      <Rodape />
      </body>
    </html>
  );
}
